services:
  mysql-standalone:
    image: mysql:8
    container_name: mysql-standalone
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bank
    networks:
      - spring-app-network

  spring-app:
    build: .
    container_name: spring-app
    restart: unless-stopped
    ports:
      - "9998:9998"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mysql-standalone
    networks:
      - spring-app-network

networks:
  spring-app-network:
    driver: bridge
