name: Banking CI Main

on:
  push:
    branches: [ '**', '!master' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'microsoft'
        cache: 'maven'
    
    - name: Build with Maven
      run: mvn clean verify

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_UNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWD }}

    - name: Build and Push Retail Banking Application to DockerHub
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: subhrodip/retail-banking:dev-${{ github.ref_name }}
        labels: |
          pipeline_build=true
          cloud_build=true
