name: Banking CI Master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'microsoft'
        cache: 'maven'
    
    - name: Build with Maven
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      env:
        # These two env variables are needed for sonar analysis
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_UNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWD }}

    - name: Build and Push Retail Banking Application to DockerHub
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: subhrodip/retail-banking:${{ github.ref_name }},subhrodip/retail-banking:latest
        labels: |
          pipeline_build=true
          cloud_build=true

    - name: Build and Push Retail Banking Application to GitHub Packages
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/ohbus/retail-banking:${{ github.ref_name }},ghcr.io/ohbus/retail-banking:latest
        labels: |
          pipeline_build=true
          cloud_build=true
